# Numpy

## 创建数组

（1）`arange`；
（2）`array`；
（3）`linespace`；
（4）`zeros`;
（5）`ones`;
（6）`empty`;
（7）`eye`；
（8）`identity`；
（9）`full`；

In [19]:
import numpy as np

# numpy.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None)
array1 = np.arange(start=1,stop=40,step=2,dtype=int,device=None,like=None).reshape(4,5)
print(array1)
print(array1.shape)         # 形状
print(array1.ndim)          # 维度
print(array1.dtype.name)    # 元素类型名
print(array1.itemsize)      # 元素大小
print(array1.size)          # 数组大小
print(type(array1))         # 类型

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]]
(4, 5)
2
int64
8
20
<class 'numpy.ndarray'>


In [17]:
# numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
array2 = np.array(object=[1,2,3,4,5,6,7,8,9],dtype=float,copy=True,order='A',subok=False,ndmin=2,like=None)
print(array2)
print(type(array2))

[[1. 2. 3. 4. 5. 6. 7. 8. 9.]]
<class 'numpy.ndarray'>


In [18]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)
array3 = np.linspace(start=1,stop=100,num=10,endpoint=True,retstep=False,dtype=None,axis=0,device=None)      # 1到100，10个数
print(array3)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [15]:
# numpy.zeros(shape, dtype=float, order='C', *, like=None)
array4 = np.zeros(shape=(3,4),dtype=int,order='C',like=None)
print(array4)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [21]:
# numpy.ones(shape, dtype=None, order='C', *, device=None, like=None)
array5 = np.ones(shape=(3,4),dtype=int,order='C',device='cpu',like=None)
print(array5)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [22]:
# numpy.empty(shape, dtype=float, order='C', *, device=None, like=None)
array6 = np.empty(shape=(3,4),dtype=int,order='F',device='cpu',like=None)
print(array6)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [26]:
# numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None, like=None)
array7 = np.eye(N=5,M=10,k=0,dtype=int,order='C',device=None,like=None)
print(array7)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]]


In [27]:
# numpy.identity(n, dtype=None, *, like=None)[source]
array8 = np.identity(n=10,dtype=int,like=None)
print(array8)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [30]:
# 
array9 = np.full(shape=(5,5),fill_value=9,dtype=int,order='F',device=None,like=None)
print(array9)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


## 

# Pandas

# Matplotlib